server: qa-cent6-64.groundwork.groundworkopensource.com
grid: none
browser: firefox
headless: false
clear_cookies: false
agent: none
name: enterprise
version: 7.0.0
bitrock_built: br288
gw_build: gw1589
